### ISSUE TITLE
Updated my config added code.

### ISSUE THREAD

**Issue by SGZ-Creations** [DeadLeavez/Leaves-ProgressiveContainer#1]
Some new content added + updated SGZ config
[mod-ts.zip](https://github.com/user-attachments/files/17204153/mod-ts.zip)
![image](https://github.com/user-attachments/assets/4a50bd41-34f9-4fa3-a5ff-71f2af2b79f2)
![image](https://github.com/user-attachments/assets/068ea48f-7d83-49b2-b34d-fe354c1b494d)

SGZ progression is used along with this preset
[secureContainers.jsonc](https://github.com/user-attachments/files/17204155/secureContainers.jsonc)
from: https://hub.sp-tarkov.com/files/file/1728-configureable-inventories/

Would be awesome to see if you would want to add this along updating you own preset thanks for an awesome mod.

**Comment by DeadLeavez** [comment]
I was planning on doing this for the 3.10 release. But this certainly helps. Thanks

**Comment by SGZ-Creations** [comment]
Re implemented the name for the case you had forgotten so my newest preset works
[mod.zip](https://github.com/user-attachments/files/18282650/mod.zip) 


Here are my preset again like it was up above when that was posted.
[S_gamez_config.jsonc](https://github.com/user-attachments/files/18282739/S_gamez_config.jsonc)
